name: awsl
description: A new Flutter project.
version: 2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  equatable: 2.0.3

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8

  image_gallery_saver: '^1.7.1'
  extended_image: ^4.0.0
  cached_network_image: 3.0.0

  flutter_staggered_grid_view: 0.5.0-dev.4
  flutter_easyrefresh: 2.2.1

  wakelock: ^0.5.6

  dio: ^4.0.0
  json_annotation: 4.4.0

  flutter_bloc: 8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  json_serializable: 6.1.1
  build_runner: ^1.0.0

flutter:
  uses-material-design: true
